### PR TITLE
LRAUV fixes to incorrect time axes in realtime contour plots and bug in .nc file generation for parameters outside of .nc4 groups

### PR DESCRIPTION
**Pull request by danellecline**

### CODE REVIEW

**Comment by stoqs** [comment]
Looks like this PR has some conflicts that must be resolved.

**Comment by duane-edgington** [comment]
When I do a “git pull” on kraken, I get the following message

(venv-stoqs)[stoqsadm@kraken CANON]$ git pull
remote: Counting objects: 61, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 61 (delta 38), reused 24 (delta 24), pack-reused 5
Unpacking objects: 100% (61/61), done.
From https://github.com/stoqs/stoqs
   7c7deba..9d5e206  master     -> origin/master
Updating 7c7deba..9d5e206
error: Your local changes to 'stoqs/loaders/CANON/realtime/Contour.py' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
(venv-stoqs)[stoqsadm@kraken CANON]$ 

OK to override Contour.py??

Duane

**Comment by duane-edgington** [comment]
Let me take a look.  Those changes should be part of a pull request. Not sure why it’s missing...


Danelle Cline
Software Engineer
Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, California  95039
831 775 1947; 831 775 1652 (fax)
www.mbari.org;  www.mbari.org/staff/dcline

**Comment by duane-edgington** [comment]
Go ahead and override

**Comment by duane-edgington** [comment]
Thanks.

This time the pull was clean

(venv-stoqs)[stoqsadm@kraken CANON]$ git pull
remote: Counting objects: 61, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 61 (delta 38), reused 24 (delta 24), pack-reused 5
Unpacking objects: 100% (61/61), done.
From https://github.com/stoqs/stoqs
   7c7deba..9d5e206  master     -> origin/master
Updating 7c7deba..9d5e206
error: Your local changes to 'stoqs/loaders/CANON/realtime/Contour.py' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
(venv-stoqs)[stoqsadm@kraken CANON]$ git pull
Updating 7c7deba..9d5e206
Fast-forward
 stoqs/loaders/CANON/loadCANON_april2017.py         |  129 +++++++++++++++-----
 stoqs/loaders/CANON/realtime/Contour.py            |   38 +++----
 stoqs/loaders/CANON/realtime/monitorLrauv.py       |   10 +-
 .../CANON/realtime/monitorLrauv_april2017.sh       |   10 +-
 stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py   |    7 +-
 stoqs/loaders/CCE/__init__.py                      |   43 +++++---
 stoqs/loaders/CCE/loadCCE_2015.py                  |    6 +-
 stoqs/loaders/__init__.py                          |   15 ++-
 8 files changed, 170 insertions(+), 88 deletions(-)
(venv-stoqs)[stoqsadm@kraken CANON]$ 

Duane

**Pull request merged**
