### PR TITLE
LRAUV loader animation/shading/boolean plots updates and changes per new Django upgrade 

### PR DESCRIPTION
**Pull request by danellecline**
LRAUV changes to add animated graphs, night time shading, boolean plot groups to plot front detection, etc. for CANON Fall experiment. Also added setup and requirements to support the new Django upgrade. The setup and requirements are separate from the core STOQS; I wasn't sure where they should go and they seemed like non-core STOQS since they aren't required for anything but the realtime LRAUV loading. They also took forever to build so would slow down the travis testing framework unnecessarily.  If you want to merge the setup and requirements with the core STOQS,  that's fine with me too. 

To use 

1.  setup a database called stoqs_canon_sept2015_lrauv
2.  add a cron job to run monitorLrauv_sep2015.sh every hour, e.g.:
0 * * * *  /opt/stoqsgit_dj1.8/stoqs/loaders/CANON/realtime/monitorLrauv_sep2015.sh >/dev/null 2>&1

### CODE REVIEW

**Comment by MBARIMike** [comment]
Those requirements can be added to requirements/production.txt and then you can remove the setup_lrauv.sh file. If you make those changes this PR can be merged and we can operate without changing our production server setup procedures.

**Comment by danellecline** [comment]
changes have been made.  Let me know how it goes.

**Comment by MBARIMike** [comment]
I'm looking in more detail to the changes for setup.sh. NetCDF4, HDF5, and basemap are great to have for production OR development. Running setup.sh with or without an argument (the default argument is 'development') will install the base libraries -- and this takes some time to download and build.

The argument to setup.sh just determines which Python requirements file to use. Perhaps the same changes made to requirements/production.txt should be made to requirements/development.txt...

**Comment by MBARIMike** [comment]
One other observation is that there should be a clear distinction between what gets installed (via yum or building from source) in provision.sh and in setup.sh. I'm not sure what that distinction is, but am identifying it here as an issue...

**Pull request merged**
