### PR TITLE
fix for --append. check if appending activity name is contained in current activity

### PR DESCRIPTION
**Pull request by duane-edgington**

### CODE REVIEW

**Comment by MBARIMike** [comment]
Addresses https://github.com/stoqs/stoqs/issues/361

**Comment by MBARIMike** [comment]
We may have been a little hasty in making [this change](https://github.com/stoqs/stoqs/pull/365/files#diff-cae62b16781823905eaf402f6b07288aR534). I think we need a function in DAPloaders.py that returns the Activity name for any combination of startdatetime and stride...

**Comment by MBARIMike** [comment]
In looking at how data is appended to existing Activities I think we can improve things by putting the dataStartDatetime lookup in the DAPloaders code and passing an append flag to the helper functions like runLrauvLoader(). This will make the CANON/__init__.py smaller and we can do more accurate Activity lookups DAPloaders.py using the new getActivityName() method.

**Comment by danellecline** [comment]
Passing in an append flag and obscuring the append logic in the DAPloaders is fine. I think we should also remove the ability for the loaders to set the activity names altogether to avoid any confusion.

**Comment by danellecline** [comment]
Any further changes to this ?

**Comment by MBARIMike** [comment]
Working on a fix now. Are you ready to help test it?

**Comment by danellecline** [comment]
Ready to help test.

**Comment by MBARIMike** [comment]
Before submitting https://github.com/stoqs/stoqs/pull/375 I confirmed successful data appending using DAPloaders.runMooringLoader() and DAPloaders.runGliderLoader(). After travis-ci says the PR is good I'll merge it. Please test that DAPloaders.runLrauvLoader() works properly for appending data.

**Pull request merged**
