### PR TITLE
Capstone Fall 2018 - Machine Learning

### PR DESCRIPTION
**Pull request by markmocek**
Introduction of machine_learning_1 Jupyter notebook. Notebook demonstrates the use of basic machine learning on the data sets collected in September 2013.  The notebook gives step-by-step directions to implement those machine learning algorithms and explore the altered data set.

### CODE REVIEW

**Comment by MBARIMike** [comment]
I'm looking in detail now at the [new notebook](https://github.com/stoqs/stoqs/blob/10136b0eb0d850292129c9eb629e1366a7cf0235/stoqs/contrib/notebooks/machine_learning_1.ipynb) and have a few comments:

1. Give directions for creating the `stoqs_september2013_o` database
2. All your plot axis labels should include the units of the parameters
3. I'm confused about the depths of salinity in cell 12 - all the depths should be between 0 and 81.7 m
4. Same for the depths of oxygen in cell 13 - but here they have a much smaller range
5. What is the purpose of the bar chart in cell 15?
6. The "Future work" section would be more relevant if it related to the STOQS data

**Comment by MBARIMike** [comment]
Happy New Year! 

I understand that the semester is over, but was wondering if there's any intention to follow up regarding [my previous comments](https://github.com/stoqs/stoqs/pull/825#issuecomment-449182482).

**Comment by mirandasaari1** [comment]
In regards to your comments we could make those changes, just to be clear:

1. We can add the directions for creating the database
2. We can add units
3. This may take some looking into, it seems like the graph uses salinity and nitrate so I am not sure why it does not mention the nitrate. This could be the reason for depth not really being depth.
4.  Same thing as (3), it uses oxygen AND bbp700, I am thinking the labels are just incorrect but I will need to check the corresponding values in the database. 
5. I did not add this, but per the text "Simple visual comparison of multiple features". Since we are already comparing oxygen and salinity we could probably remove this graph. If that is okay with @markmocek or @bretstine (I am not sure who made this graph).
6. Which particular parts do you feel don't contribute to the goal of STOQS? (e.g. semi supervised learning, time series modeling for patterns, trends among depths, expanding to other platforms)

**Comment by mirandasaari1** [comment]
@MBARIMike where would I be able to find the units? I was exploring the UI and only some attributes seemed to appear. I am looking for the units for Nitrate, Oxygen, bbp700, and verifying salinity would be 1e-3

Also here are the changes I have made so far and questions I still have 
1. I changed the database name to stoqs_september2013_o in the instructions, was there more you wanted changed/added? (I am just following the instructions per the other notebooks)
2. reference my question above
3. Changed the graph/description to the correct labels
4. Same as 3
5. @bretstine will need to answer this
6. Please refernce my last comment for my question.

**Comment by MBARIMike** [comment]
The [Measured Parameter Data Access Parquet export option](https://github.com/stoqs/stoqs/issues/837) is a game changer for enabling more efficient machine learning operations on STOQS data. This PR really did expose the need that is now satisfied by the Parquet export option.

**Comment by stoqs** [comment]
Looking forward to new machine learning projects using the Parquet export option!

**Pull request closed without merging**
