### PR TITLE
Contour plot radio buttons

### PR DESCRIPTION
**Pull request by samuelrey**
Applies to #230 
Pull request for the 2017 Spring capstone work on the STOQS contour lines feature.

### CODE REVIEW

**Comment by MBARIMike** [comment]
Small nit: Please edit this Pull Request to give it an appropriate title and put `https://github.com/stoqs/stoqs/issues/230` in the description.

**Comment by samuelrey** [comment]
The travis failures are linked to missing gecko-drivers. I'm unsure whether that was a result of code we've added.

**Comment by MBARIMike** [comment]
The test.sh script exits with the return code from the unit tests, so this is the error report that matters:
```
Unit tests...
Creating test database for alias 'default'...
.............................E.........
======================================================================
ERROR: test_parameterplot_scatter (stoqs.tests.unit_tests.SummaryDataTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "stoqs/tests/unit_tests.py", line 349, in test_parameterplot_scatter
    img_path = os.path.join(settings.MEDIA_ROOT, 'sections/', data.get('parameterplatformdatavaluepng')[0])
  File "/home/travis/miniconda2/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by noemicuin** [comment]
while running the stoqs application, i'm confused as to why there's an error when selecting the Plot radio button. The error reads, "Problem with getting parameter-contour-plot-radio button info" this is happening for both the Sampled & Measured Parameters.

**Comment by J0S349** [comment]
Hey Mike, we wanted to know if you could point us to your most recent and working commit. When we meet last, your application was working correctly, and we are still running into the same issue as before. 

https://github.com/stoqs/stoqs/issues/230#issuecomment-296818928

**Comment by MBARIMike** [comment]
My guess is that [this commit](https://github.com/stoqs/stoqs/pull/578/commits/f4a5b24b8a22f479d517241189a1a7615dc36a58) is originated the error. The commit is fine, the problem is in the logic of `getParameterPlatformDatavaluePNG()`: now that it is dealing with 2 plotting options its logic needs to be reworked. Let me work on that. Look for a PR soon.

**Comment by MBARIMike** [comment]
@samuelrey Please merge https://github.com/samuelrey/stoqs/pull/4 so that it it gets added to this PR.

**Pull request merged**
