### PR TITLE
Refine cluster.py script

### PR DESCRIPTION
**Pull request by MBARIMike**
Applies to https://github.com/stoqs/stoqs/issues/624.

### CODE REVIEW

**Comment by MBARIMike** [comment]
Executing:

```
stoqs/contrib/analysis/cluster.py --saveClustersSeq --database stoqs_september2013_t --platform Slocum_260 --inputs optical_backscatter700nm fluorescence --algorithm DBSCAN --labeledGroupName DBSCANclusters --interval hours=1 --algorithm DBSCAN --start 20130910T185850 --end 20131001T153321 -v
```
Works, but creates multiple labeledGroupNames:

screen shot 2017-08-04 at 2 31 02 pm

**Comment by rkahnMBARI** [comment]
I wrote the script to create multiple labeledGroupNames... I thought it would be the best way to keep the different time steps distinct within the database so that eventually one can track a cluster over time.

**Comment by MBARIMike** [comment]
Removing labels works:

```
stoqs/contrib/analysis/cluster.py --removeLabelsSeq --database stoqs_september2013_t --platform Slocum_260 --inputs optical_backscatter700nm fluorescence --algorithm DBSCAN --labeledGroupName DBSCANclusters --interval hours=1 --algorithm DBSCAN --start 20130910T185850 --end 20131001T153321
```
Good!

**Comment by MBARIMike** [comment]
Note: For better testing of displaying updated data in the UI disable caching by commenting out the `'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',` line and uncommenting the `'BACKEND': 'django.core.cache.backends.dummy.DummyCache',` in `stoqs/config/settings/local.py`:

```diff
diff --git a/stoqs/config/settings/local.py b/stoqs/config/settings/local.py
index 38ec4b8..1ec96a1 100644
--- a/stoqs/config/settings/local.py
+++ b/stoqs/config/settings/local.py
@@ -33,8 +33,8 @@ EMAIL_BACKEND = env('DJANGO_EMAIL_BACKEND',
 # ------------------------------------------------------------------------------
 CACHES = {
     'default': {
-        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
-        ##'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
+        ##'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
+        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
         'LOCATION': ''
     }
 }
```

**Comment by MBARIMike** [comment]
Here's what I had in mind with the use of `--labeledGroupName`. Execute multiple clustering operations, e.g.:

```
stoqs/contrib/analysis/cluster.py --labeledGroupName DBSCANclusters --saveClustersSeq --database stoqs_september2013_t --platform Slocum_260 --inputs optical_backscatter700nm fluorescence --algorithm DBSCAN  --interval hours=1 --start 20130910T185850 --end 20131001T153321
stoqs/contrib/analysis/cluster.py --labeledGroupName Mean_Shiftclusters --saveClustersSeq --database stoqs_september2013_t --platform Slocum_260 --inputs optical_backscatter700nm fluorescence --algorithm Mean_Shift --interval hours=1 --start 20130910T185850 --end 20131001T153321
```
They are then grouped together in the UI:
screen shot 2017-08-04 at 4 29 52 pm

**Comment by rkahnMBARI** [comment]
Ah, I see. That does look better, but how to will you store the clusters for each time step so that each step can be accessed individually (like to make the trajectory biplot movie)?

**Comment by MBARIMike** [comment]
Testing on development VM with this moderate resolution load from loadCANON_september2013.py:
```python
    cl.loadDaphne(stride=2)
    cl.loadTethys(stride=2)
    cl.load_slocum_260(stride=10)
    cl.load_slocum_294(stride=10)
```
This load took less than 22 hours to complete from my home network.

**Comment by MBARIMike** [comment]
After the measuredparameters are labeled (it's the Resource, not the ResourceType that matters here) we can iterate again over time to make the trajectory biplot movie, separately coloring the individual labels (Resources).

**Comment by MBARIMike** [comment]
Testing on development VM with this moderate resolution load from loadCANON_september2013.py:
```python
    cl.loadDaphne(stride=2)
    cl.loadTethys(stride=2)
    cl.load_slocum_260(stride=10)
    cl.load_slocum_294(stride=10)
```
This load took less than 22 hours to complete from my home network.

**Comment by MBARIMike** [comment]
This command on the development system with [these data loaded](https://github.com/stoqs/stoqs/pull/626#issuecomment-320393884):
```
stoqs/contrib/analysis/cluster.py --saveClustersSeq --database stoqs_september2013 --platform Slocum_260 --inputs optical_backscatter700nm fluorescence --algorithm Mean_Shift --clusteredGroupName Mean_Shift-Slocum_260 --interval hours=1 --step minutes=30 --start 20130910T185850 --end 20131001T153321 -v
```
took about 10 minutes to finish.

This execution:
```
stoqs/contrib/analysis/trajectory_biplots.py -d stoqs_september2013 -p Slocum_260 -x optical_backscatter700nm -y fluorescence --plotDir /tmp --plotPrefix stoqs_september2013_ --hourStep 1 --hourWindow 2 --xLabel optical_backscatter700nm --yLabel fluorescence --title 'Slocum_260 Mean_Shift' --minDepth 0 --maxDepth 200 --start 20130910T185850 --end 20131001T153321 --groupName Mean_Shift-Slocum_260 -v
convert -delay 10 /tmp/stoqs_september2013_Slocum_260_Mean_Shift_*.png /tmp/stoqs_september2013_Slocum_260_Mean_Shift.gif
ffmpeg -r 10 -i /tmp/stoqs_september2013_Slocum_260_Mean_Shift.gif -vcodec mpeg4 -qscale 1 -y /tmp/stoqs_september2013_Slocum_260_Mean_Shift.mp4
```
also took about 10 minutes and produced an intrersting video, here's a clip of it:
stoqs_september2013_slocum_260_mean_shift1-9

**Comment by MBARIMike** [comment]
The video clip is intriguing. It's nice to see the different colors; however, I have suspicions that things are not correct. Further analysis and evaluation are needed. To make it easier for others to test the code this PR will be merged.

**Pull request merged**
